#!/usr/bin/env python3
"""Render docs/evidence/decomp-campaign/DASHBOARD.md from an objdiff report.

The numbers here come from `build/progress.json`, i.e. from objdiff comparing
each SKIP_ASM-built object against the retail target -- the same measure
decomp.dev ingests. Nothing is hand-maintained, and INCLUDE_ASM'd functions
cannot inflate it: under -DSKIP_ASM they are absent from the compared object.

Usage:
    python3 tools/scripts/progress_dashboard.py [-i build/progress.json] [-o <md>]
"""
from __future__ import annotations

import argparse
import datetime
import json
import pathlib
import re

REPO = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_IN = REPO / "build" / "progress.json"
DEFAULT_OUT = REPO / "docs" / "evidence" / "decomp-campaign" / "DASHBOARD.md"


def m(obj: dict, key: str, default=0):
    """objdiff emits some measures as strings (u64 in JSON); coerce."""
    v = obj.get("measures", {}).get(key, default)
    if isinstance(v, str):
        try:
            return int(v)
        except ValueError:
            return float(v)
    return v


def bar(pct: float, width: int = 24) -> str:
    filled = int(round(pct / 100 * width))
    return "#" * filled + "." * (width - filled)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("-i", "--input", type=pathlib.Path, default=DEFAULT_IN)
    ap.add_argument("-o", "--output", type=pathlib.Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    report = json.loads(args.input.read_text())
    today = datetime.date.today().isoformat()

    code_pct = m(report, "matched_code_percent")
    fn_pct = m(report, "matched_functions_percent")
    fuzzy = m(report, "fuzzy_match_percent")

    out: list[str] = []
    A = out.append
    A("# Xenogears Decompilation Progress")
    A("")
    A(f"_Generated by `tools/scripts/progress_dashboard.py` from `{args.input.relative_to(REPO)}`_")
    A(f"_objdiff report version {report.get('version')} · {today}_")
    A("")
    A("## How to read this")
    A("")
    A("Progress is **matched bytes against the retail target**, the measure")
    A("objdiff and decomp.dev use. Objects are built with `-DSKIP_ASM`, so a")
    A("function still carried as `INCLUDE_ASM` contributes its full size to the")
    A("denominator and **nothing** to the numerator.")
    A("Port-only semantic reconstructions tagged `/* FAKEMATCH */` are not")
    A("byte-exact matches and are excluded; see `docs/FAKEMATCHES.md`.")
    A("")
    A("This is a harsher bar than \"the ROM rebuilds byte-identically\" -- that is true of")
    A("several overlays already and says nothing about how much C exists.")
    A("")
    A("| Measure | Value |")
    A("|---|---|")
    A(f"| **Code matched** | **{code_pct:.2f}%** ({m(report,'matched_code'):,} / {m(report,'total_code'):,} bytes) |")
    A(f"| Functions fully matched | {fn_pct:.2f}% ({m(report,'matched_functions'):,} / {m(report,'total_functions'):,}) |")
    A(f"| Fuzzy match | {fuzzy:.2f}% |")
    A(f"| Units (objects) | {m(report,'total_units'):,} |")
    A("")
    A("## Per overlay")
    A("")
    A("Note: `Psy-Q SDK` is a *subset* of `Main Executable` "
      "(`slus_006.64/psyq` inside `slus_006.64`), so those two rows overlap "
      "and do not sum to the total.")
    A("")
    A("| Overlay | Code matched | Bytes | Functions | Progress |")
    A("|---|---:|---|---:|---|")
    cats = sorted(report.get("categories", []),
                  key=lambda c: -m(c, "total_code"))
    for c in cats:
        tc = m(c, "total_code")
        if not tc:
            continue
        p = m(c, "matched_code_percent")
        A(f"| {c['name']} | {p:.2f}% | {m(c,'matched_code'):,} / {tc:,} | "
          f"{m(c,'matched_functions'):,} / {m(c,'total_functions'):,} | `{bar(p)}` |")
    A("")

    # ---- burn-down: biggest unmatched code, which is where the work is ----
    units = report.get("units", [])
    ranked = sorted(units, key=lambda u: -(m(u, "total_code") - m(u, "matched_code")))
    A("## Burn-down — largest unmatched objects")
    A("")
    A("Sorted by unmatched bytes: the top of this list is where decompilation")
    A("effort moves the headline number most.")
    A("")
    A("| Unit | Unmatched bytes | Code matched | Functions |")
    A("|---|---:|---:|---:|")
    for u in ranked[:30]:
        tc, mc = m(u, "total_code"), m(u, "matched_code")
        if tc - mc <= 0:
            break
        A(f"| `{u['name']}` | {tc-mc:,} | {m(u,'matched_code_percent'):.1f}% | "
          f"{m(u,'matched_functions')}/{m(u,'total_functions')} |")
    A("")

    done = [u for u in units if m(u, "total_code") and
            m(u, "matched_code") == m(u, "total_code")]
    A(f"## Fully matched units — {len(done)} of {len(units)}")
    A("")
    A("Every function in these objects is byte-identical to retail with no")
    A("`INCLUDE_ASM` remaining.")
    A("")
    for u in sorted(done, key=lambda u: -m(u, "total_code"))[:40]:
        A(f"- `{u['name']}` ({m(u,'total_code'):,} bytes, {m(u,'total_functions')} fns)")
    if len(done) > 40:
        A(f"- _... and {len(done)-40} more_")
    A("")
    # ---- coverage: what the report cannot see at all ----
    A("## Coverage holes — code this report does NOT measure")
    A("")
    A("`objdiff` only sees modules the build system builds. Anything missing")
    A("from `gears.toml`'s `overlays` list is absent from both the numerator")
    A("**and the denominator**, so the headline above is not a fraction of the")
    A("whole game.")
    A("")
    built = set()
    gears = (REPO / "gears.toml").read_text()
    for line in gears.splitlines():
        if line.startswith("overlays"):
            built |= set(re.findall(r'"([^"]+)"', line))
    built.add("slus_006.64")
    rows, missing_bytes = [], 0
    disc = REPO / "disc"
    for p in sorted(disc.glob("*")):
        stem = p.name[:-4] if p.name.endswith(".bin") else p.name
        if p.suffix in (".chd", ".cue") or stem.lower() in ("disc1", "scph5500"):
            continue
        if not p.is_file() or p.name.startswith("."):
            continue
        is_built = stem in built or stem.lower() == "slus_006.64"
        size = p.stat().st_size
        if not is_built:
            missing_bytes += size
        rows.append((stem, size, is_built))
    A("| Retail module | Size | In the build? |")
    A("|---|---:|---|")
    for stem, size, ok in sorted(rows, key=lambda r: -r[1]):
        A(f"| `{stem}` | {size:,} | {'built + measured' if ok else '**NOT BUILT — unmeasured**'} |")
    total_retail = sum(r[1] for r in rows)
    A("")
    A(f"**{missing_bytes:,} of {total_retail:,} retail bytes "
      f"({missing_bytes/total_retail*100:.1f}%) are in modules the build does "
      f"not produce at all.**")
    A("")
    A("Also check `config/checksum.sha`, which is the byte-exactness gate: it")
    A("must list every module you intend to match. A module that is built but")
    A("absent from that file is never checked.")
    A("")
    A("## Regenerating")
    A("")
    A("```")
    A("make report                                      # builds + writes build/progress.json")
    A("python3 tools/scripts/progress_dashboard.py      # rewrites this file")
    A("```")
    A("")
    A("`make report` runs `gears report`, which passes `-DSKIP_ASM` and skips")
    A("linking, so the currently-red slus link does not block it.")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out) + "\n")
    print(f"wrote {args.output.relative_to(REPO)}  "
          f"({code_pct:.2f}% code, {fn_pct:.2f}% functions)")


if __name__ == "__main__":
    main()
