#!/usr/bin/env python3
"""Convert the public-domain Jiskan 16 HEX font into the port's KROM layout."""

from __future__ import annotations

import hashlib
import pathlib
import sys

EXPECTED_SHA256 = "cb177cddeb3cf73bd3e62dc93a7db1ad8c162256a50b93ecf7fc3bd641ea26d1"
GRID = 94 * 94
GLYPH_BYTES = 32
# These public-domain cells happen to be identical to 32-byte runs in the
# local retail BIOS image. Keep the port binary free of those bytes; render the
# rare punctuation cells as blank rather than triggering the retail-data guard.
RETAIL_OVERLAP_CELLS = {"2169", "224f"}


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit(f"usage: {sys.argv[0]} SOURCE.hex OUTPUT.inc")
    source = pathlib.Path(sys.argv[1])
    output = pathlib.Path(sys.argv[2])
    raw = source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != EXPECTED_SHA256:
        raise SystemExit(f"unexpected Jiskan source hash: {digest}")

    glyphs = [bytes(GLYPH_BYTES) for _ in range(GRID)]
    for line_number, raw_line in enumerate(raw.splitlines(), 1):
        line = raw_line.decode("ascii")
        code, bitmap = line.split(":", 1)
        row, cell = int(code[:2], 16), int(code[2:], 16)
        if not (0x21 <= row <= 0x7E and 0x21 <= cell <= 0x7E):
            raise SystemExit(f"invalid JIS cell at {source}:{line_number}: {code}")
        glyph = bytes.fromhex(bitmap)
        if len(glyph) != GLYPH_BYTES:
            raise SystemExit(f"invalid glyph size at {source}:{line_number}: {code}")
        index = (row - 0x21) * 94 + cell - 0x21
        glyphs[index] = bytes(GLYPH_BYTES) if code.lower() in RETAIL_OVERLAP_CELLS else glyph

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="ascii", newline="\n") as stream:
        stream.write("/* Generated by pc_port/tools/gen_jiskan16.py; public-domain glyph data. */\n")
        for glyph in glyphs:
            stream.write("    {" + ",".join(f"0x{byte:02x}" for byte in glyph) + "},\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
