#!/usr/bin/env python3
"""Emit a retail<->native field map for a struct in include/system/menu.h.

The native port inflates menu structs (8-byte host pointers), so a retail
differential test must mirror native fields into a retail-layout guest block.
Retail offsets come from the header's `/* 0xNNN */` comments; the element's
retail size is the distance to the next member.  Output: a C initializer
list of {retail_off, native_off, retail_elem, native_elem, count, is_ptr, name}.

usage: gen_struct_mirror.py <StructName> <retail_total_size_hex> > out.inc
"""
import re, sys, pathlib
name, total = sys.argv[1], int(sys.argv[2], 16)
text = pathlib.Path(__file__).resolve().parents[3].joinpath("include/system/menu.h").read_text()
end = text.index("} %s;" % name)
start = text.rindex("typedef struct", 0, end)
body = text[start:end]
mem = re.compile(r'/\*\s*(0x[0-9A-Fa-f]+)\s*\*/\s*([A-Za-z_][\w \t]*?(?:\*\s*)?)\b(\w+)\s*(?:\[([^\]]+)\])?\s*;')
rows = []
for m in mem.finditer(body):
    off, typ, field, dim = int(m.group(1), 16), m.group(2), m.group(3), m.group(4)
    rows.append([off, typ.strip(), field, dim])
for i, r in enumerate(rows):
    nxt = rows[i + 1][0] if i + 1 < len(rows) else total
    r.append(nxt - r[0])
print("/* generated by pc_port/tests/lib/gen_struct_mirror.py %s */" % name)
for off, typ, field, dim, span in rows:
    ptr = "*" in typ
    cnt = "(sizeof(((%s*)0)->%s) / sizeof(((%s*)0)->%s[0]))" % (name, field, name, field) if dim else "1"
    nel = "sizeof(((%s*)0)->%s%s)" % (name, field, "[0]" if dim else "")
    print("    {0x%X, offsetof(%s, %s), 0x%X, %s, %s, %d, \"%s\"}," % (off, name, field, span, nel, cnt, int(ptr), field))
