#!/usr/bin/env python3
"""Relocation-aware, instruction-for-instruction comparison of a matching-build
object against the retail listings generated by `gears matching`.

Retail authority: asm/field/**/<tu>/<func>.s, one `/* off addr word */` comment
per instruction (word is the little-endian ROM byte string). Built side:
`objdump -dr` of the object. Instructions carrying a relocation are compared on
their opcode/register bits with the relocated field masked, and the relocation
symbol (and %lo addend) is compared against the retail operand text. A `j` to a
section-local label is compared as a function-relative displacement.

Exit status is 0 only when every retail function in the listing set is EXACT
and the object carries no text symbols absent from retail (unless --allow-extra).

usage: field_vm_retail_compare.py --objdump TOOL --obj FILE --asm DIR [--asm DIR]
                                  [--expect-tu-bytes N] [--json OUT] [--verbose]
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

RETAIL_LINE = re.compile(
    r'^\s*/\* ([0-9A-F]+) ([0-9A-F]{8}) ([0-9A-F]{8}) \*/\s+(\S+)\s*(.*?)\s*$')
GLABEL = re.compile(r'^glabel (\S+)')
OBJ_FUNC = re.compile(r'^([0-9a-f]+) <([^>]+)>:$')
OBJ_INSN = re.compile(r'^\s*([0-9a-f]+):\s+([0-9a-f]{8})\s+(\S+)\s*(.*?)\s*$')
OBJ_RELOC = re.compile(r'^\s*([0-9a-f]+): (R_MIPS_\S+)\s+(\S+)$')
RETAIL_HI = re.compile(r'%hi\(([^)]+)\)')
RETAIL_LO = re.compile(r'%lo\(([^)]+)\)')
RETAIL_GP = re.compile(r'%gp_rel\(([^)]+)\)')


def parse_retail(dirs):
    funcs = {}
    for d in dirs:
        for path in sorted(Path(d).glob('*.s')):
            name = None
            insns = []
            for line in path.read_text().splitlines():
                m = GLABEL.match(line)
                if m:
                    name = m.group(1)
                    continue
                m = RETAIL_LINE.match(line)
                if m and name:
                    addr = int(m.group(2), 16)
                    word = int.from_bytes(bytes.fromhex(m.group(3)), 'little')
                    insns.append((addr, word, m.group(4), m.group(5)))
            if name:
                funcs[name] = insns
    return funcs


def parse_object(objdump, obj):
    text = subprocess.run([objdump, '-dr', '-j', '.text', obj],
                          check=True, capture_output=True, text=True).stdout
    funcs = {}
    order = []
    cur = None
    for line in text.splitlines():
        m = OBJ_FUNC.match(line)
        if m:
            cur = m.group(2)
            funcs[cur] = {'start': int(m.group(1), 16), 'insns': []}
            order.append(cur)
            continue
        if cur is None:
            continue
        m = OBJ_RELOC.match(line)
        if m:
            off = int(m.group(1), 16)
            for ins in reversed(funcs[cur]['insns']):
                if ins['off'] == off:
                    ins['relocs'].append((m.group(2), m.group(3)))
                    break
            continue
        m = OBJ_INSN.match(line)
        if m:
            funcs[cur]['insns'].append({
                'off': int(m.group(1), 16), 'word': int(m.group(2), 16),
                'mn': m.group(3), 'ops': m.group(4), 'relocs': []})
    return funcs, order


def split_sym(expr):
    """'g_Scene + 0xC4' -> ('g_Scene', 0xC4); 'D_x' -> ('D_x', 0)."""
    expr = expr.strip()
    m = re.match(r'^([A-Za-z_.$][\w.$]*)\s*([+-])\s*(0x[0-9A-Fa-f]+|\d+)$', expr)
    if m:
        off = int(m.group(3), 0)
        return m.group(1), off if m.group(2) == '+' else -off
    return expr, 0


def split_reloc_sym(sym):
    """objdump prints 'sym+0xc4' or 'sym-0x10' or 'sym'."""
    m = re.match(r'^(.*?)([+-]0x[0-9a-fA-F]+)$', sym)
    if m:
        return m.group(1), int(m.group(2), 16)
    return sym, 0


def sext16(v):
    v &= 0xFFFF
    return v - 0x10000 if v & 0x8000 else v


def compare_insn(b, r, built_func_start, retail_func_addr):
    """Return None if equivalent, else a short reason string."""
    r_addr, r_word, r_mn, r_ops = r
    if not b['relocs']:
        if b['word'] != r['word'] if isinstance(r, dict) else b['word'] != r_word:
            return 'word %08x != retail %08x' % (b['word'], r_word)
        return None
    rtype, rsym = b['relocs'][0]
    if rtype in ('R_MIPS_HI16', 'R_MIPS_LO16', 'R_MIPS_GPREL16', 'R_MIPS_LITERAL', 'R_MIPS_GOT16'):
        mask = 0xFFFF
    elif rtype == 'R_MIPS_26':
        mask = 0x03FFFFFF
    else:
        return 'unhandled reloc %s' % rtype
    if (b['word'] & ~mask) != (r_word & ~mask):
        return 'opcode/regs %08x != retail %08x under %s' % (b['word'], r_word, rtype)
    bsym, badd = split_reloc_sym(rsym)
    if rtype == 'R_MIPS_26':
        if bsym == '.text':
            # local jump: compare function-relative displacement
            b_target = ((b['word'] & mask) << 2) + badd if badd else (b['word'] & mask) << 2
            r_target = ((r_word & mask) << 2) | (r_addr & 0xF0000000)
            if (b_target - built_func_start) != (r_target - retail_func_addr):
                return 'local j target disp %#x != retail %#x' % (
                    b_target - built_func_start, r_target - retail_func_addr)
            return None
        # jal symbol
        rs = r_ops.strip()
        if bsym != rs:
            return 'call %s != retail %s' % (bsym, rs)
        return None
    m = (RETAIL_HI if rtype == 'R_MIPS_HI16' else
         RETAIL_GP if rtype == 'R_MIPS_GPREL16' else RETAIL_LO).search(r_ops)
    if not m:
        return 'retail operand lacks %s expression: %s' % (rtype, r_ops)
    rsymn, radd = split_sym(m.group(1))
    if bsym != rsymn:
        return 'symbol %s != retail %s' % (bsym, rsymn)
    # objdump folds the in-instruction addend into the symbol for LO16 on REL
    # targets ("sym+0xc4"); otherwise the addend is the sign-extended imm16.
    if rtype in ('R_MIPS_LO16', 'R_MIPS_GPREL16'):
        b_addend = badd if badd else sext16(b['word'])
        if b_addend != radd:
            return 'addend %#x != retail %#x for %s' % (b_addend, radd, bsym)
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--objdump', required=True)
    ap.add_argument('--obj', required=True)
    ap.add_argument('--asm', action='append', required=True)
    ap.add_argument('--expect-tu-bytes', type=int)
    ap.add_argument('--json')
    ap.add_argument('--verbose', action='store_true')
    ap.add_argument('--allow-extra', action='store_true')
    ap.add_argument('--max-diff-lines', type=int, default=12)
    args = ap.parse_args()

    retail = parse_retail(args.asm)
    built, order = parse_object(args.objdump, args.obj)

    rows = []
    ok = True
    for name in sorted(retail, key=lambda n: retail[n][0][0]):
        r = retail[name]
        row = {'function': name, 'retail_addr': '%08X' % r[0][0],
               'retail_bytes': 4 * len(r)}
        if name not in built:
            row.update(status='MISSING', built_bytes=0)
            ok = False
            rows.append(row)
            continue
        b = built[name]
        row['built_bytes'] = 4 * len(b['insns'])
        row['built_offset'] = '%x' % b['start']
        diffs = []
        n = min(len(b['insns']), len(r))
        for i in range(n):
            why = compare_insn(b['insns'][i], r[i], b['start'], r[0][0])
            if why:
                diffs.append((i, why, b['insns'][i], r[i]))
        if len(b['insns']) != len(r):
            row['status'] = 'SIZE %+d bytes' % (4 * (len(b['insns']) - len(r)))
            ok = False
        elif diffs:
            row['status'] = 'MISMATCH %d/%d' % (len(diffs), len(r))
            ok = False
        else:
            row['status'] = 'EXACT'
        row['diff_count'] = len(diffs)
        row['first_divergence'] = ('%08X' % r[diffs[0][0]][0]) if diffs else None
        row['diffs'] = [
            {'index': i, 'retail_addr': '%08X' % rr[0], 'why': why,
             'built': '%s %s' % (bb['mn'], bb['ops']),
             'retail': '%s %s' % (rr[2], rr[3])}
            for i, why, bb, rr in diffs[:args.max_diff_lines]]
        rows.append(row)

    extra = [(n, 4 * len(built[n]['insns'])) for n in order if n not in retail]
    if extra and not args.allow_extra:
        ok = False

    tu_built = sum(4 * len(built[n]['insns']) for n in built)
    tu_retail = sum(4 * len(v) for v in retail.values())

    print('%-36s %-10s %8s %8s %6s  %s' % ('function', 'retail', 'retail_B', 'built_B', 'delta', 'status'))
    for row in sorted(rows, key=lambda r: -(r['retail_bytes'] - r['built_bytes'])):
        print('%-36s %-10s %8d %8d %+6d  %s' % (
            row['function'], row['retail_addr'], row['retail_bytes'],
            row['built_bytes'], row['built_bytes'] - row['retail_bytes'], row['status']))
        if args.verbose:
            for d in row['diffs']:
                print('    [%4d] %s  retail@%s: %s | built: %s' % (
                    d['index'], d['why'], d['retail_addr'], d['retail'], d['built']))
    for n, sz in extra:
        print('%-36s %-10s %8s %8d %6s  EXTRA built-only symbol' % (n, '-', '-', sz, ''))
    print('TU .text: built %d bytes, retail listings %d bytes, delta %+d' % (
        tu_built, tu_retail, tu_built - tu_retail))
    if args.expect_tu_bytes is not None:
        print('TU expectation %d: %s' % (args.expect_tu_bytes,
              'MET' if tu_built == args.expect_tu_bytes else 'NOT MET'))
        if tu_built != args.expect_tu_bytes:
            ok = False
    order_ok = [n for n in order if n in retail] == sorted(
        [n for n in order if n in retail], key=lambda n: retail[n][0][0])
    print('TU function order matches retail: %s' % ('yes' if order_ok else 'NO'))
    if not order_ok:
        ok = False
    print('RESULT: %s' % ('ALL EXACT' if ok else 'NOT EXACT'))
    if args.json:
        Path(args.json).write_text(json.dumps({
            'rows': rows, 'extra_symbols': extra, 'tu_built_bytes': tu_built,
            'tu_retail_bytes': tu_retail, 'order_ok': order_ok, 'all_exact': ok},
            indent=1) + '\n')
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
