#!/usr/bin/env bash
#
# Regression certificate for the retail encounter-section object
# D_800658DC / D_80065ADC (weights at +0x200).
#
# Links the real production owners -- pc_port/src/data_field.c (the aliased
# storage) and src/field/main/misc4.c (the real func_80079288 weighted roll) --
# against an explicit-spy driver, then proves the same test detects the defect
# by rebuilding it against deliberately mutated copies of data_field.c that
# MUST fail.
#
# Undefined references from the two production TUs (everything not yet ported)
# are tolerated with --unresolved-symbols=ignore-all; the tested path touches
# only symbols this test defines or that data_field.c owns.
set -euo pipefail
cd "$(dirname "$0")/../.."
ulimit -c 0

OUT=${ENCOUNTER_WEIGHT_OUT:-$(mktemp -d /tmp/xeno-encounter-weight.XXXXXXXX)}
mkdir -p "$OUT"
echo "ENCOUNTER WEIGHT OUTPUT $OUT"

DATA_FIELD=pc_port/src/data_field.c
MISC4=src/field/main/misc4.c
DRIVER=pc_port/tests/encounter_weight_aliasing_prod_test.c

# Same flags the port build uses for these TUs (pc_port/build_port.sh).
CFLAGS=(-std=gnu17 -fpermissive -DXENO_PC_PORT -DXENO_FIELD_OBJECT_OVERLAY
        -DSKIP_ASM -D_LANGUAGE_C -DUSE_EXTENDED_PRIM_POINTERS=0
        -include assert.h -w -O0 -g -m64 -fno-builtin
        -Ipc_port/include_shim -Iinclude -Ipc_port/build_native -Ipc_port/src
        -Ipc_port/extern/PsyCross/include -Ipc_port/extern/PsyCross/include/psx)
LDFLAGS=(-m64 -no-pie -fno-pie -Wl,--unresolved-symbols=ignore-all)

# ---------------------------------------------------------------------------
# Structural pins: the fix must be present in the production sources, and the
# old split-object definition must be gone.
# ---------------------------------------------------------------------------
python3 - "$DATA_FIELD" pc_port/src/game_overrides.c <<'PY'
import re, sys
data_field, overrides = (open(p).read() for p in sys.argv[1:3])

block = re.search(r'^unsigned char g_SlusBss_800658DC\[(0x[0-9A-Fa-f]+)\]', data_field, re.M)
assert block, "data_field.c: missing g_SlusBss_800658DC backing block"
size = int(block.group(1), 16)
assert size >= 0x230, f"backing block is 0x{size:X}, retail span needs >= 0x230"

assert data_field.count('FIELD_BSS_ALIAS(D_800658DC, g_SlusBss_800658DC, 0x000);') == 1, \
    "data_field.c: D_800658DC must alias the shared block at +0x000"
assert data_field.count('FIELD_BSS_ALIAS(D_80065ADC, g_SlusBss_800658DC, 0x200);') == 1, \
    "data_field.c: D_80065ADC must alias the shared block at +0x200"

assert not re.search(r'^\s*u8\s+D_80065ADC\s*\[', overrides, re.M), \
    "game_overrides.c still defines a standalone D_80065ADC; the split object is back"
print("ENCOUNTER WEIGHT STRUCTURE OK (block 0x%X, aliases +0x000/+0x200)" % size)
PY

# The generated stub manifest must not carry a competing definition, or the
# port link fails with a duplicate symbol. It is regenerated by build_port.sh
# from the trial link's undefined references, so this only needs a rebuild.
if grep -q '^unsigned char D_800658DC\[' pc_port/build_native/stubs.c 2>/dev/null; then
    echo "ENCOUNTER WEIGHT WARNING: pc_port/build_native/stubs.c still defines D_800658DC."
    echo "  It is a stale generated artifact: re-run pc_port/build_port.sh (with the"
    echo "  matching ELFs present) to regenerate it, or the port link will report"
    echo "  'multiple definition of D_800658DC'."
fi

# ---------------------------------------------------------------------------
# Production build + run.
# ---------------------------------------------------------------------------
# misc4.o and the driver are identical for every variant; only data_field.c
# changes. Build them once (this also keeps the /tmp footprint small).
gcc "${CFLAGS[@]}" -c "$MISC4"  -o "$OUT/misc4.o"
gcc "${CFLAGS[@]}" -c "$DRIVER" -o "$OUT/driver.o"

build_and_run() {
    local label="$1" data_field_src="$2"
    gcc "${CFLAGS[@]}" -c "$data_field_src" -o "$OUT/$label.data_field.o"
    gcc "${LDFLAGS[@]}" "$OUT/$label.data_field.o" "$OUT/misc4.o" \
        "$OUT/driver.o" -o "$OUT/$label"
    rm -f "$OUT/$label.data_field.o"
    set +e
    "$OUT/$label" > "$OUT/$label.log" 2>&1
    local rc=$?
    set -e
    rm -f "$OUT/$label"
    return $rc
}

rc=0
build_and_run production "$DATA_FIELD" || rc=$?
cat "$OUT/production.log"
if [ "$rc" != 0 ] || ! grep -q '^ENCOUNTER WEIGHT PASS$' "$OUT/production.log"; then
    echo "ENCOUNTER WEIGHT production case failed (rc=$rc)" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Controls: each mutated layout MUST be rejected by the same assertions.
# ---------------------------------------------------------------------------
python3 - "$DATA_FIELD" "$OUT" <<'PY'
import json, sys
from pathlib import Path
source = Path(sys.argv[1]).read_text()
out = Path(sys.argv[2])

BLOCK = 'unsigned char g_SlusBss_800658DC[0x230] __attribute__((aligned(8)));\n'
A0    = 'FIELD_BSS_ALIAS(D_800658DC, g_SlusBss_800658DC, 0x000);\n'
A200  = 'FIELD_BSS_ALIAS(D_80065ADC, g_SlusBss_800658DC, 0x200);\n'
whole = BLOCK + A0 + A200
assert source.count(whole) == 1, "anchor for mutation not found exactly once"

controls = {
    # The exact pre-fix layout: two unrelated objects, sized as the generated
    # stub (0x200 * 2) and the old game_overrides.c definition.
    'split-objects':
        'unsigned char D_800658DC[1024] __attribute__((aligned(8)));\n'
        'unsigned char D_80065ADC[16] __attribute__((aligned(8)));\n',
    # Weight window 16 bytes short of the record area's end.
    'weights-at-0x1F0': BLOCK + A0 +
        'FIELD_BSS_ALIAS(D_80065ADC, g_SlusBss_800658DC, 0x1F0);\n',
    # Weight window 16 bytes past it (lands on the 2-byte tail + slack).
    'weights-at-0x210': BLOCK + A0 +
        'FIELD_BSS_ALIAS(D_80065ADC, g_SlusBss_800658DC, 0x210);\n',
}
paths = {}
for name, replacement in controls.items():
    assert replacement != whole, name
    path = out / (name + '.c')
    path.write_text(source.replace(whole, replacement))
    paths[name] = str(path)
(out / 'controls.json').write_text(json.dumps(paths, indent=2) + '\n')
PY

rejected=0
for control in split-objects weights-at-0x1F0 weights-at-0x210; do
    rc=0
    build_and_run "$control" "$OUT/$control.c" || rc=$?
    if [ "$rc" != 1 ] || ! grep -q '^ENCOUNTER WEIGHT FAIL ' "$OUT/$control.log"; then
        cat "$OUT/$control.log"
        echo "ENCOUNTER WEIGHT control failed to detect defect: $control rc=$rc" >&2
        exit 1
    fi
    echo "ENCOUNTER WEIGHT CONTROL REJECTED $control"
    rejected=$((rejected + 1))
done

echo "ENCOUNTER WEIGHT CONTROLS REJECTED $rejected/3"
echo "ENCOUNTER WEIGHT OK"
